services:
  server:
    build:
      context: .
      dockerfile: local-dcl.dockerfile
    image: "local-dcl"
    container_name: local-dcl
    ports:
      - "8000:8000"
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - ./ota_firmware:/ota_firmware:rw

#     networks:
#       - server_default

# networks:
#   server_default:
#     external: true